The code herein is presented to illustrate two portfolio allocation methods (described below).  Following the imports of relevant libraries, 4 basic inputs are defined:
- `cash`
- `number_of_investments`
- `target_pcts`
- `current_values`

The utility of the portfolio allocation methods will vary depending on the inputs.  Sometimes, portfolio allocation is so straightforward, it requires little-to-no math.  Other times, portfolio allocation can require advanced methods.  To appreciate this, look at the existing output before running any code.  You will see a scenario in which Method 1 is suboptimal and Method 2 is required to achieve an optimal allocation.  To explore other scenarios, the existing code will generate random values for `cash` and `current_values`.  

To explore even further, the current default values for `number_of_investments` and `target_pcts` can be replaced with the commented out code, however; note that such variety will often generate uninteresting scenarios.  The methods presented here are most useful when there are significant discrepancies between current and target values across many but not all investments, and there is a large amount of `cash` to allocate but not enough meet all target values.

# Data Preparation

In [1]:
#import relevant libraries
import pandas as pd
import numpy as np
from random import randint
import sympy as sp

In [55]:
#Define the basic features of the portfolio and investment

#cash is the money to be allocated to investments
cash = np.random.randint(1000,10000); print('cash = ',cash)

#The ultility of the functions below depends on a set of conditions that are captured by the defult inputs used here.  
#However, the script will work with random values (generated by the commented out code) for the sake of experimenting
number_of_investments = 10#np.random.randint(3,20)

#target_pcts are the set of target allocations specified as proportions that sum to 1 (minus rounding error)
def create_target_pcts(n_i):
    n = 20 - n_i
    arr = [1] * n_i
    for i in range(n):
        arr[randint(0, n) % n_i] += 1
    return [(5*x)/100 for x in arr]
target_pcts = [.1,.1,.1,.1,.1,.1,.1,.1,.1,.1]#create_targets(number_of_investments)
assert round(df['target%'].sum()) == 1, 'sum of target % allocations do not equal zero'

#current_values are the current values of the investments in the portfolio
current_values = np.random.randint(10,1000, size=number_of_investments)

#create DataFrame
df = pd.DataFrame({'target%':target_pcts,'current_value':current_values})
df

cash =  2810

   target%  current_value
0      0.1            190
1      0.1            183
2      0.1            696
3      0.1            223
4      0.1            136
5      0.1             90
6      0.1            923
7      0.1             39
8      0.1            731
9      0.1            315

In [56]:
# Create calculated columns which will be used by the functions below.
    # note that target values reflect cash as shown in calculation
df['current%'] = df['current_value'] / df['current_value'].sum()
df['target_value'] = df['target%'] * (df['current_value'].sum()+cash)
df['deficit'] = df['target_value'] - df['current_value']
df['error'] = (df['current_value'] / df['current_value'].sum()) - df['target%']

# create 'rank column' to reflect rankings of deficits (i.e., discrepancies between the target and current values)
    # rankings are made in descending order such that the largest deficit gets a rank of 0
df['rank'] = df['deficit'].rank(method='first',ascending=False).astype(int)-1

# having the dataframe sorted by rank makes calculations subsequent easier to interpret
df.sort_values(by='rank',inplace=True)
df

   target%  current_value  current%  target_value  deficit     error  rank
7      0.1             39  0.011061         633.6    594.6 -0.088939     0
5      0.1             90  0.025525         633.6    543.6 -0.074475     1
4      0.1            136  0.038571         633.6    497.6 -0.061429     2
1      0.1            183  0.051900         633.6    450.6 -0.048100     3
0      0.1            190  0.053885         633.6    443.6 -0.046115     4
3      0.1            223  0.063244         633.6    410.6 -0.036756     5
9      0.1            315  0.089336         633.6    318.6 -0.010664     6
2      0.1            696  0.197391         633.6    -62.4  0.097391     7
8      0.1            731  0.207317         633.6    -97.4  0.107317     8
6      0.1            923  0.261770         633.6   -289.4  0.161770     9

# Method 1: allocate-by-rank

This method allocates cash to completely eliminate the deficits in rank order untill the cash is gone.  For example, if the cash is \\$3 and the two top ranking deficits are each \\$2, 
this method will result in an allocation of \\$2 to the top ranking deficit and \\$1 to the subsequent deficit.

In [66]:
#define function to determine allocation based on the index of the DataFrame and the amonut allocated so far
    #The function allocates an amount equal to the deficit or whatever dollars remain 
    #after accounting for previous allocations
    
def determine_amount(i,allocated_so_far):
    if (df.loc[i,'deficit'] <= cash - allocated_so_far) & (df.loc[i,'deficit']>=0): 
        return df.loc[i,'deficit']
    elif (df.loc[i,'deficit'] >= cash - allocated_so_far) & (df.loc[i,'deficit']>=0): 
         return cash - allocated_so_far
    elif df.loc[i,'deficit'] < 0:
        return 0

#find the allocation to each investment
total_allocation = 0
money = cash
allocated_cumsum = 0
for rank in df['rank']:
    b = df['rank']==rank
    index = df.loc[b].index[0]
    allocation = determine_amount(index,allocated_cumsum)
    df.loc[b,'allocate_by_rank'] = allocation
    allocated_cumsum += allocation
    money = cash - allocated_cumsum

#calculate the error of the new values
df['error2'] = ((df['current_value'] + df['allocate_by_rank']) / (df['current_value'].sum()+cash)) - df['target%']

print('cash = ',cash)
df

cash =  2810

,target%,current_value,current%,target_value,deficit,error,rank,allocate_by_rank,error2
7,0.1,39,0.011061,633.6,594.6,-0.088939,0,594.6,0.000000
5,0.1,90,0.025525,633.6,543.6,-0.074475,1,543.6,0.000000
4,0.1,136,0.038571,633.6,497.6,-0.061429,2,497.6,0.000000
1,0.1,183,0.051900,633.6,450.6,-0.048100,3,450.6,0.000000
0,0.1,190,0.053885,633.6,443.6,-0.046115,4,443.6,0.000000
3,0.1,223,0.063244,633.6,410.6,-0.036756,5,280.0,-0.020612
9,0.1,315,0.089336,633.6,318.6,-0.010664,6,0.0,-0.050284
2,0.1,696,0.197391,633.6,-62.4,0.097391,7,0.0,0.009848
8,0.1,731,0.207317,633.6,-97.4,0.107317,8,0.0,0.015372
6,0.1,923,0.261770,633.6,-289.4,0.161770,9,0.0,0.045676

In [65]:
#make sure the sum of the allocations equals the cash
assert round(df['allocate_by_rank'].sum()) == cash, "sum of investments doesn't equal cash"

#check to see if method 2 will be useful or not
b1 = df['deficit'] >= 0
b2 = df['allocate_by_rank'] > 0
if df.loc[b1&b2,'error2'].abs().min() < df.loc[b1&~b2,'error2'].abs().max():
    print('you need Method 2')
else:
    print("Method 2 is unnecessary and may return nonsense")

you need invest_4_equal_errors

# Method 2: allocate-for-equal-errors

Method 1 can lead to suboptimal results.  When allocating cash to elminate deficits, 
errors are reduced to zero for investments with the top ranking deficits, 
but may remain large for investments with lower ranking deficits.  The optimal result would be a set of allocations that minimizes all errors as much as possible.  

Method 2 achieves this by calculating the minimum possible error for all investments with a deficit greater than 0,
and then calculating the allocations required to produce those errors.

In [75]:
# For illustrate purposes, create system of equations required to calculate the minimum equal error 
# achievable for investments with a deficit greater than 0
    
# The first set of equations are derived from the same equation used to calculate the "error" columns above
    # the symbol e is reserved for error
    # all other single, lowercase, letter symbols represent allocations
cv = df['current_value'].to_list()
t_pct = df['target%'].to_list()
from sympy.abc import *
equations = {}
allocation_symbols = []
b = df['deficit'] >= 0
deficit_cnt = df.loc[b,'rank'].max()
for I,S in enumerate('abcdfghijklmnopqrstuvwxyz'[:deficit_cnt+1]):
    allocation_symbols.append(symbols(S))
    equations.update({'eq'+str(I):(((cv[I] + symbols(S)) / (sum(cv)+cash)) - t_pct[I]) - e})

# The final equation reflects the constraint that the sum of all allocations should equal the cash available to allocate
equations.update({'eq'+str(deficit_cnt+1):sum(allocation_symbols) - cash})
display('System of equations: ',equations)

#solve the system of equations
symbol_values = sp.solve(equations.values(), allocation_symbols+[e])

#make sure that the sum of the allocations is equal to the cash available to allocate
assert sum([symbol_values[S] for S in symbol_values if S != e]) == cash, 'sum of allocations != cash'

{'eq0': a/6336 - e - 0.093844696969697,
 'eq1': b/6336 - e - 0.0857954545454545,
 'eq2': c/6336 - e - 0.0785353535353535,
 'eq3': d/6336 - e - 0.0711174242424242,
 'eq4': -e + f/6336 - 0.0700126262626263,
 'eq5': -e + g/6336 - 0.0648042929292929,
 'eq6': -e + h/6336 - 0.0502840909090909,
 'eq7': a + b + c + d + f + g + h - 2810}

In [76]:
#Calculate equal errors
#The equation for e is derived from the system of equations presented above
cv = df['current_value'].to_list()
t_pct = df['target%'].to_list()
deficit = df['deficit'].to_list()
select_ranks = [i for i in range(len(df)) if deficit[i]>0]
select_cv = sum([cv[i] for i in select_ranks])
select_t_pct = sum([t_pct[i] for i in select_ranks])
select_ranks_cnt = len(ranks)
e = 1/select_ranks_cnt * ((select_cv + cash)/(sum(cv) + cash) - select_t_pct)

#calculate cash allocations in a dictionary where keys are ranks and values are allocations
#the equation for each allocation is derived from the system of equations presented above
allocations = {i:((e + t_pct[i])*(sum(cv)+cash)) - cv[i] if i in select_ranks else 0 for i in range(len(df))}

#create column containing allocations calculated via Method 2
df['allocate_=ez'] = df.apply(lambda r: totals[r['rank']],axis=1)

#Calculate errors based on Method 2 allocations
df['error3'] = ((df['current_value'] + df['allocate_=ez']) / (df['current_value'].sum()+cash)) - df['target%']

df

,target%,current_value,current%,target_value,deficit,error,rank,allocate_by_rank,error2,invest_=ez,error3
0,0.1,39,0.011061,633.6,594.6,-0.088939,0,594.6,0.000000,530.428571,-0.010128
1,0.1,90,0.025525,633.6,543.6,-0.074475,1,543.6,0.000000,479.428571,-0.010128
2,0.1,136,0.038571,633.6,497.6,-0.061429,2,497.6,0.000000,433.428571,-0.010128
3,0.1,183,0.051900,633.6,450.6,-0.048100,3,450.6,0.000000,386.428571,-0.010128
4,0.1,190,0.053885,633.6,443.6,-0.046115,4,443.6,0.000000,379.428571,-0.010128
5,0.1,223,0.063244,633.6,410.6,-0.036756,5,280.0,-0.020612,346.428571,-0.010128
6,0.1,315,0.089336,633.6,318.6,-0.010664,6,0.0,-0.050284,254.428571,-0.010128
7,0.1,696,0.197391,633.6,-62.4,0.097391,7,0.0,0.009848,0.000000,0.009848
8,0.1,731,0.207317,633.6,-97.4,0.107317,8,0.0,0.015372,0.000000,0.015372
9,0.1,923,0.261770,633.6,-289.4,0.161770,9,0.0,0.045676,0.000000,0.045676

As shown in the output above, Method 1 and Method 2 result in different allocations.  By comparing the error columns, we can see that Method 2 optimizes errors across investments by minimizing them as much as possible.  

While the portfolio size and allocation amounts are relatively small, the difference between optimal and suboptimal allocations may have significant consequences for larger portfolios with larger allocation amounts.  In high stakes situations such as hedge funds, company-owned assests, or government budget distributions, or philanthropic initiatives, 
allocation methods could impact overall portfolio or program performance and the recipients of the funding determined by the allocation method.